### ISSUE TITLE
Nested routes (more than 1 level)

### ISSUE THREAD

**Issue by d4nicoder** [edgarnadal/vue-tidyroutes#1]
When I try to configure 2 levels of nested routes, it doesn't export well, for example:
```javascript
VueTidyRoutes.route('/main', {
	name: 'Principal',
	component: Main
})

VueTidyRoutes.route('/main').child('panel', {
	name: 'Panel de control',
	component: PanelControl
})

VueTidyRoutes.route('/main').child('panel').child('gestion_empresas', {
	name: 'Gestión de empresas',
	component: GestionEmpresas
})
```
In this case when I export, '/main/panel' route has no childs, and route 'gestion_empresas' appears as a child of '/main'

Am I doing something wrong?

Thansk and congratulations ;)

(PS: Sorry about my english)

**Comment by edgarnadal** [comment]
Hi @danitetus I'll check on that.

**Comment by edgarnadal** [comment]
Hi @danitetus,

I was checking on your request but right now is not supported (you are welcome to make a PR with that).

The thing is .child returns an instance of it's parent route so you can chain multiple childs.

```
Routes.route('/component2')
    .child('child-3', {
        name: 'child-3',
        component: ChildComponent3
    })
    .child('child-4', {
        name: 'child-4',
        component: ChildComponent4
    });
```

**Comment by edgarnadal** [comment]
So I was talking with @javisperez about your issue and he told me that you can use the VueRouter nested capabilities, it's ugly but it works.

```
Routes.route('/component2')
    .child('child-3', {
        name: 'child-3',
        component: ChildComponent3,
        children: [ // here you have to use the format expected by vue not tidyroutes. https://router.vuejs.org/en/essentials/nested-routes.html
            {
                path: 'child-4',
                component: ChildComponent4
            }
        ]
    });
```
