### ISSUE TITLE
Setting child&children path '/childpath' will not work but works without '/'

### ISSUE THREAD

**Issue by shocklinbaubau** [edgarnadal/vue-tidyroutes#2]
When I need a path: /campaign/example-base

This works:
`VueTidyRoutes.route('/campaign', {
  component: () => import('./views/TheCampaignLayout.vue'),
  children: {
    'example-base': {
      component: () => import(`./templates/example-base/App.vue`)
    }
  }
})`

This do not work:
`VueTidyRoutes.route('/campaign', {
  component: () => import('./views/TheCampaignLayout.vue'),
  children: {
    '/example-base': {
      component: () => import(`./templates/example-base/App.vue`)
    }
  }
})`

And also
This works:
`VueTidyRoutes.route('/campaign').child('example-base', {
  component: () => import(`./templates/example-base/App.vue`),
  children: ExampleBaseTemplateRoutes
})`

This do not work
`VueTidyRoutes.route('/campaign').child('/example-base', {
  component: () => import(`./templates/example-base/App.vue`),
  children: ExampleBaseTemplateRoutes
})`

Please update document, this typo has eaten me a day.

**Comment by edgarnadal** [comment]
Thanks for your report! I just published v0.1.4 fixing this and now it will work.
